// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Start_Job_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Start_Job_date));
        
        string IMigrationMetadata.Id
        {
            get { return "202212090549365_Start_Job_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
