// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TestLazyLoading : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestLazyLoading));
        
        string IMigrationMetadata.Id
        {
            get { return "202211100307007_TestLazyLoading"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
