// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_PeriodName_OPeriodLesson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_PeriodName_OPeriodLesson));
        
        string IMigrationMetadata.Id
        {
            get { return "202211170844341_Add_PeriodName_OPeriodLesson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
